Q			=@
OBJDIR  	=../obj
BINDIR  	=../bin
TARGET		=lib_MQTTAgent_64.a
MAKEFILE	=linux.mk
RM			=rm -r -f

all:
	$(Q)make -f $(MAKEFILE)

clean:
	$(Q)echo "  Cleaning '$(TARGET)' ..."
	$(Q)$(RM) $(OBJDIR)
	$(Q)$(RM) $(OUTPATH)