FROM       icap_coreservice_base:v1.6.1
WORKDIR /root
# RUN apt-get install -y libevent-2.0-5
COPY iCAP_CoreService_NotificationService  /root/iCAP_CoreService_NotificationService
ENTRYPOINT ["./iCAP_CoreService_NotificationService"]