Q			=@
OBJDIR  	=../obj
BINDIR  	=../bin
TARGET		=lib_mongodb_64.a
MAKEFILE	=linux.mk
RM			=rm -r -f

.PHONY: all
all:
	$(Q)make -f $(MAKEFILE)

.PHONY: clean
clean:
	$(Q)echo "  Cleaning '$(TARGET)' ..."
	$(Q)$(RM) $(OBJDIR)
	$(Q)$(RM) $(OUTPATH)