// export const VERSION_NUMBER = GLOBAL_VARIABLES.VERSION_NUMBER;

export const BG_COLOR_01 = GLOBAL_VARIABLES.BG_COLOR_01;
export const BG_COLOR_02 = GLOBAL_VARIABLES.BG_COLOR_02;
export const BG_COLOR_03 = GLOBAL_VARIABLES.BG_COLOR_03;
export const BG_COLOR_04 = GLOBAL_VARIABLES.BG_COLOR_04;
export const BG_COLOR_05 = GLOBAL_VARIABLES.BG_COLOR_05;
export const BG_COLOR_06 = GLOBAL_VARIABLES.BG_COLOR_06;
export const BG_COLOR_07 = GLOBAL_VARIABLES.BG_COLOR_07;

export const CHART_BASE_COLOR_A = GLOBAL_VARIABLES.CHART_BASE_COLOR_A;
export const CHART_BASE_COLOR_B = GLOBAL_VARIABLES.CHART_BASE_COLOR_B;
export const CHART_BASE_COLOR_C = GLOBAL_VARIABLES.CHART_BASE_COLOR_C;
export const CHART_BASE_COLOR_D = GLOBAL_VARIABLES.CHART_BASE_COLOR_D;
export const CHART_BASE_COLOR_E = GLOBAL_VARIABLES.CHART_BASE_COLOR_E;
export const CHART_BASE_COLOR_F = GLOBAL_VARIABLES.CHART_BASE_COLOR_F;

export const FONT_COLOR_A = GLOBAL_VARIABLES.FONT_COLOR_A;
export const FONT_COLOR_B = GLOBAL_VARIABLES.FONT_COLOR_B;
export const FONT_COLOR_C = GLOBAL_VARIABLES.FONT_COLOR_C;
export const FONT_COLOR_D = GLOBAL_VARIABLES.FONT_COLOR_D;
export const FONT_COLOR_E = GLOBAL_VARIABLES.FONT_COLOR_E;

export const HIGHLIGHT_COLOR = GLOBAL_VARIABLES.HIGHLIGHT_COLOR;

export const LOGINFORM_LEFT_LOGO = GLOBAL_VARIABLES.LOGINFORM_LEFT_LOGO;
export const LOGINFORM_RIGHT_LOGO = GLOBAL_VARIABLES.LOGINFORM_RIGHT_LOGO;
export const HEADER_LOGO = GLOBAL_VARIABLES.HEADER_LOGO;
export const LEFT_SIDEBAR_TOP_LOGO = GLOBAL_VARIABLES.LEFT_SIDEBAR_TOP_LOGO;
export const LEFT_SIDEBAR_BOTTOM_LOGO = GLOBAL_VARIABLES.LEFT_SIDEBAR_BOTTOM_LOGO;

export const DEFAULT_COLOR = 'rgb(109, 174, 219, 0.7)';

export const DASHBOARD_TOP_NAVBAR_BG_COLOR = GLOBAL_VARIABLES.DASHBOARD_TOP_NAVBAR_BG_COLOR;
export const DASHBOARD_TOP_NAVBAR_COLOR = GLOBAL_VARIABLES.DASHBOARD_TOP_NAVBAR_COLOR;
export const DASHBOARD_TOP_NAVBAR_HEIGHTLIGHT_COLOR = GLOBAL_VARIABLES.DASHBOARD_TOP_NAVBAR_HEIGHTLIGHT_COLOR

export const MOCK_OOB = GLOBAL_VARIABLES.OOB === 'MOCK';

export const ENABLE_SSL = GLOBAL_VARIABLES.SSL;